CANDIDATE_STATE_NEW = "NEW"
CANDIDATE_STATE_CONTACT_COLLECTED = "CONTACT_COLLECTED"
CANDIDATE_STATE_CONSENTED = "CONSENTED"
CANDIDATE_STATE_ROLE_CONFIRMED = "ROLE_CONFIRMED"
CANDIDATE_STATE_CV_PENDING = "CV_PENDING"
CANDIDATE_STATE_CV_PROCESSING = "CV_PROCESSING"
CANDIDATE_STATE_SUMMARY_REVIEW = "SUMMARY_REVIEW"
CANDIDATE_STATE_QUESTIONS_PENDING = "QUESTIONS_PENDING"
CANDIDATE_STATE_VERIFICATION_PENDING = "VERIFICATION_PENDING"
CANDIDATE_STATE_READY = "READY"
CANDIDATE_STATE_UNDER_MANAGER_REVIEW = "UNDER_MANAGER_REVIEW"
CANDIDATE_STATE_APPROVED = "APPROVED"
CANDIDATE_STATE_REJECTED = "REJECTED"

CANDIDATE_READY_LIKE_STATES = frozenset(
    {
        CANDIDATE_STATE_READY,
        CANDIDATE_STATE_UNDER_MANAGER_REVIEW,
        CANDIDATE_STATE_APPROVED,
        CANDIDATE_STATE_REJECTED,
    }
)


def normalize_candidate_operational_state(state):
    if state in {
        CANDIDATE_STATE_UNDER_MANAGER_REVIEW,
        CANDIDATE_STATE_APPROVED,
        CANDIDATE_STATE_REJECTED,
    }:
        return CANDIDATE_STATE_READY
    return state
