/**
 * Canonical events across matching and interview orchestration.
 *
 * This is a contract-only layer. Runtime wiring is intentionally not added yet.
 */
export const MATCHING_EVENTS = {
  MATCH_CREATED: "MATCH_CREATED",
  MATCH_INVITATION_SENT: "MATCH_INVITATION_SENT",
  MATCH_ACCEPTED: "MATCH_ACCEPTED",
  MATCH_DECLINED: "MATCH_DECLINED",
  INTERVIEW_STARTED: "INTERVIEW_STARTED",
  INTERVIEW_ANSWER_RECORDED: "INTERVIEW_ANSWER_RECORDED",
  INTERVIEW_COMPLETED: "INTERVIEW_COMPLETED",
  EVALUATION_COMPLETED: "EVALUATION_COMPLETED",
  CANDIDATE_SENT_TO_MANAGER: "CANDIDATE_SENT_TO_MANAGER",
  MANAGER_APPROVED_CANDIDATE: "MANAGER_APPROVED_CANDIDATE",
  MANAGER_REJECTED_CANDIDATE: "MANAGER_REJECTED_CANDIDATE",
} as const;

export type MatchingEvent = (typeof MATCHING_EVENTS)[keyof typeof MATCHING_EVENTS];

