import { HELLY_ACTIONS, HellyAction } from "./actions";
import { HELLY_STATES, HellyState } from "./states";

/**
 * Declarative state -> allowed action contract.
 *
 * Not enforced yet by runtime. This map is intended for the future
 * gatekeeper/state-engine extraction.
 */
export const allowedActions: Record<HellyState, HellyAction[]> = {
  [HELLY_STATES.WAIT_CONTACT]: [
    HELLY_ACTIONS.START,
    HELLY_ACTIONS.SHARE_CONTACT,
    HELLY_ACTIONS.SHARE_PHONE_TEXT,
    HELLY_ACTIONS.SKIP_FOR_NOW,
    HELLY_ACTIONS.CANCEL,
  ],
  [HELLY_STATES.WAIT_ROLE]: [
    HELLY_ACTIONS.SELECT_ROLE_CANDIDATE,
    HELLY_ACTIONS.SELECT_ROLE_MANAGER,
    HELLY_ACTIONS.HELP,
    HELLY_ACTIONS.START,
  ],
  [HELLY_STATES.CONTACT_SHARED]: [
    HELLY_ACTIONS.SELECT_ROLE_CANDIDATE,
    HELLY_ACTIONS.SELECT_ROLE_MANAGER,
    HELLY_ACTIONS.START,
  ],

  [HELLY_STATES.C_ONBOARDING_INTRO]: [
    HELLY_ACTIONS.SUBMIT_CV,
    HELLY_ACTIONS.SUBMIT_TEXT,
    HELLY_ACTIONS.SUBMIT_FILE,
    HELLY_ACTIONS.START,
  ],
  [HELLY_STATES.C_WAIT_CV]: [
    HELLY_ACTIONS.SUBMIT_CV,
    HELLY_ACTIONS.SUBMIT_TEXT,
    HELLY_ACTIONS.SUBMIT_FILE,
    HELLY_ACTIONS.SUBMIT_VOICE,
    HELLY_ACTIONS.CANCEL,
  ],
  [HELLY_STATES.C_CV_PROCESSING]: [
    HELLY_ACTIONS.CANCEL,
    HELLY_ACTIONS.HELP,
  ],
  [HELLY_STATES.C_SUMMARY_REVIEW]: [
    HELLY_ACTIONS.APPROVE,
    HELLY_ACTIONS.EDIT,
    HELLY_ACTIONS.SUBMIT_TEXT,
    HELLY_ACTIONS.CANCEL,
  ],
  [HELLY_STATES.C_SUMMARY_EDIT]: [
    HELLY_ACTIONS.SUBMIT_TEXT,
    HELLY_ACTIONS.APPROVE,
    HELLY_ACTIONS.CANCEL,
  ],
  [HELLY_STATES.C_MANDATORY_QUESTIONNAIRE]: [
    HELLY_ACTIONS.ANSWER_QUESTION,
    HELLY_ACTIONS.SUBMIT_TEXT,
    HELLY_ACTIONS.SHARE_LOCATION,
    HELLY_ACTIONS.CANCEL,
  ],
  [HELLY_STATES.C_MANDATORY_LOCATION]: [
    HELLY_ACTIONS.SUBMIT_TEXT,
    HELLY_ACTIONS.SHARE_LOCATION,
    HELLY_ACTIONS.CANCEL,
  ],
  [HELLY_STATES.C_MANDATORY_WORK_FORMAT]: [
    HELLY_ACTIONS.SUBMIT_TEXT,
    HELLY_ACTIONS.CANCEL,
  ],
  [HELLY_STATES.C_MANDATORY_SALARY]: [
    HELLY_ACTIONS.SUBMIT_TEXT,
    HELLY_ACTIONS.YES,
    HELLY_ACTIONS.NO,
    HELLY_ACTIONS.CANCEL,
  ],
  [HELLY_STATES.C_VIDEO_VERIFICATION_WAIT]: [
    HELLY_ACTIONS.SUBMIT_VIDEO,
    HELLY_ACTIONS.CANCEL,
  ],
  [HELLY_STATES.C_READY]: [
    HELLY_ACTIONS.RUN_MATCHING,
    HELLY_ACTIONS.SHOW_MATCHES,
    HELLY_ACTIONS.PAUSE_MATCHING,
    HELLY_ACTIONS.RESUME_MATCHING,
    HELLY_ACTIONS.UPDATE_LOCATION,
    HELLY_ACTIONS.UPDATE_WORK_MODE,
    HELLY_ACTIONS.UPDATE_SALARY,
    HELLY_ACTIONS.DELETE_PROFILE,
  ],
  [HELLY_STATES.C_MATCH_OFFERED]: [
    HELLY_ACTIONS.YES,
    HELLY_ACTIONS.NO,
    HELLY_ACTIONS.CANCEL,
  ],
  [HELLY_STATES.C_INTERVIEW_IN_PROGRESS]: [
    HELLY_ACTIONS.ANSWER_QUESTION,
    HELLY_ACTIONS.SUBMIT_TEXT,
    HELLY_ACTIONS.SUBMIT_VOICE,
    HELLY_ACTIONS.SKIP_QUESTION,
    HELLY_ACTIONS.FINISH_INTERVIEW,
    HELLY_ACTIONS.CANCEL,
  ],
  [HELLY_STATES.C_INTERVIEW_COMPLETED]: [
    HELLY_ACTIONS.SHOW_MATCHES,
    HELLY_ACTIONS.RUN_MATCHING,
  ],

  [HELLY_STATES.HM_ONBOARDING_INTRO]: [
    HELLY_ACTIONS.SUBMIT_JD,
    HELLY_ACTIONS.SUBMIT_TEXT,
    HELLY_ACTIONS.SUBMIT_FILE,
    HELLY_ACTIONS.SUBMIT_VOICE,
    HELLY_ACTIONS.SUBMIT_VIDEO,
    HELLY_ACTIONS.START,
  ],
  [HELLY_STATES.HM_WAIT_JD]: [
    HELLY_ACTIONS.SUBMIT_JD,
    HELLY_ACTIONS.SUBMIT_TEXT,
    HELLY_ACTIONS.SUBMIT_FILE,
    HELLY_ACTIONS.SUBMIT_VOICE,
    HELLY_ACTIONS.SUBMIT_VIDEO,
    HELLY_ACTIONS.CANCEL,
  ],
  [HELLY_STATES.HM_JD_PROCESSING]: [
    HELLY_ACTIONS.CANCEL,
    HELLY_ACTIONS.HELP,
  ],
  [HELLY_STATES.HM_JD_REVIEW]: [
    HELLY_ACTIONS.APPROVE,
    HELLY_ACTIONS.EDIT,
    HELLY_ACTIONS.SUBMIT_TEXT,
    HELLY_ACTIONS.CANCEL,
  ],
  [HELLY_STATES.HM_JD_EDIT]: [
    HELLY_ACTIONS.SUBMIT_TEXT,
    HELLY_ACTIONS.APPROVE,
    HELLY_ACTIONS.CANCEL,
  ],
  [HELLY_STATES.HM_QUESTIONNAIRE]: [
    HELLY_ACTIONS.ANSWER_QUESTION,
    HELLY_ACTIONS.SUBMIT_TEXT,
    HELLY_ACTIONS.CANCEL,
  ],
  [HELLY_STATES.HM_MANDATORY_WORK_FORMAT]: [
    HELLY_ACTIONS.SUBMIT_TEXT,
    HELLY_ACTIONS.UPDATE_WORK_FORMAT,
    HELLY_ACTIONS.CANCEL,
  ],
  [HELLY_STATES.HM_MANDATORY_COUNTRIES]: [
    HELLY_ACTIONS.SUBMIT_TEXT,
    HELLY_ACTIONS.UPDATE_COUNTRIES,
    HELLY_ACTIONS.CANCEL,
  ],
  [HELLY_STATES.HM_MANDATORY_BUDGET]: [
    HELLY_ACTIONS.SUBMIT_TEXT,
    HELLY_ACTIONS.UPDATE_BUDGET,
    HELLY_ACTIONS.YES,
    HELLY_ACTIONS.NO,
    HELLY_ACTIONS.CANCEL,
  ],
  [HELLY_STATES.HM_VACANCY_OPEN]: [
    HELLY_ACTIONS.RUN_MATCHING,
    HELLY_ACTIONS.SHOW_MATCHES,
    HELLY_ACTIONS.PAUSE_MATCHING,
    HELLY_ACTIONS.RESUME_MATCHING,
    HELLY_ACTIONS.UPDATE_WORK_FORMAT,
    HELLY_ACTIONS.UPDATE_COUNTRIES,
    HELLY_ACTIONS.UPDATE_BUDGET,
    HELLY_ACTIONS.DELETE_VACANCY,
  ],
  [HELLY_STATES.HM_MATCH_REVIEW]: [
    HELLY_ACTIONS.YES,
    HELLY_ACTIONS.NO,
    HELLY_ACTIONS.SHOW_MATCHES,
  ],
  [HELLY_STATES.HM_INTERVIEW_IN_PROGRESS]: [
    HELLY_ACTIONS.ANSWER_QUESTION,
    HELLY_ACTIONS.SUBMIT_TEXT,
    HELLY_ACTIONS.SUBMIT_VOICE,
    HELLY_ACTIONS.SKIP_QUESTION,
    HELLY_ACTIONS.FINISH_INTERVIEW,
    HELLY_ACTIONS.CANCEL,
  ],
  [HELLY_STATES.HM_INTERVIEW_COMPLETED]: [
    HELLY_ACTIONS.SHOW_MATCHES,
    HELLY_ACTIONS.RUN_MATCHING,
  ],

  [HELLY_STATES.WAIT_CANDIDATE_DECISION]: [
    HELLY_ACTIONS.YES,
    HELLY_ACTIONS.NO,
    HELLY_ACTIONS.SHARE_CONTACT,
    HELLY_ACTIONS.CANCEL,
  ],
  [HELLY_STATES.WAIT_MANAGER_DECISION]: [
    HELLY_ACTIONS.YES,
    HELLY_ACTIONS.NO,
    HELLY_ACTIONS.SHARE_CONTACT,
    HELLY_ACTIONS.CANCEL,
  ],

  [HELLY_STATES.C_DELETE_PROFILE_CONFIRM_1]: [
    HELLY_ACTIONS.CONFIRM_DELETE_PROFILE,
    HELLY_ACTIONS.CANCEL,
  ],
  [HELLY_STATES.C_DELETE_PROFILE_CONFIRM_2]: [
    HELLY_ACTIONS.CONFIRM_DELETE_PROFILE,
    HELLY_ACTIONS.CANCEL,
  ],
  [HELLY_STATES.HM_DELETE_VACANCY_CONFIRM_1]: [
    HELLY_ACTIONS.CONFIRM_DELETE_VACANCY,
    HELLY_ACTIONS.CANCEL,
  ],
  [HELLY_STATES.HM_DELETE_VACANCY_CONFIRM_2]: [
    HELLY_ACTIONS.CONFIRM_DELETE_VACANCY,
    HELLY_ACTIONS.CANCEL,
  ],
};
