/**
 * Domain events emitted by Helly workflows.
 * These are typed contracts only and are not yet wired to runtime emitters.
 */
export const HELLY_EVENTS = {
  // Session and identity
  CONTACT_SHARED: "CONTACT_SHARED",
  CONTACT_SKIPPED: "CONTACT_SKIPPED",
  ROLE_SELECTED: "ROLE_SELECTED",

  // Candidate intake and readiness
  CV_SUBMITTED: "CV_SUBMITTED",
  CV_PROCESSED: "CV_PROCESSED",
  CV_APPROVED: "CV_APPROVED",
  CV_EDITED: "CV_EDITED",
  CANDIDATE_MANDATORY_LOCATION_SET: "CANDIDATE_MANDATORY_LOCATION_SET",
  CANDIDATE_MANDATORY_WORK_FORMAT_SET: "CANDIDATE_MANDATORY_WORK_FORMAT_SET",
  CANDIDATE_MANDATORY_SALARY_SET: "CANDIDATE_MANDATORY_SALARY_SET",
  CANDIDATE_VIDEO_VERIFICATION_SUBMITTED: "CANDIDATE_VIDEO_VERIFICATION_SUBMITTED",
  CANDIDATE_READY: "CANDIDATE_READY",

  // Manager vacancy intake and readiness
  JD_SUBMITTED: "JD_SUBMITTED",
  JD_PROCESSED: "JD_PROCESSED",
  JD_APPROVED: "JD_APPROVED",
  JD_EDITED: "JD_EDITED",
  MANAGER_WORK_FORMAT_SET: "MANAGER_WORK_FORMAT_SET",
  MANAGER_ALLOWED_COUNTRIES_SET: "MANAGER_ALLOWED_COUNTRIES_SET",
  MANAGER_BUDGET_SET: "MANAGER_BUDGET_SET",
  VACANCY_OPENED: "VACANCY_OPENED",
  VACANCY_UPDATED: "VACANCY_UPDATED",

  // Matching and interview lifecycle
  MATCHING_REQUESTED: "MATCHING_REQUESTED",
  MATCH_FOUND: "MATCH_FOUND",
  INTERVIEW_STARTED: "INTERVIEW_STARTED",
  INTERVIEW_ANSWER_ACCEPTED: "INTERVIEW_ANSWER_ACCEPTED",
  INTERVIEW_SKIPPED_QUESTION: "INTERVIEW_SKIPPED_QUESTION",
  INTERVIEW_COMPLETED: "INTERVIEW_COMPLETED",
  FINAL_EVALUATION_COMPLETED: "FINAL_EVALUATION_COMPLETED",

  // Decisions and handoff
  CANDIDATE_APPROVED_BY_MANAGER: "CANDIDATE_APPROVED_BY_MANAGER",
  CANDIDATE_REJECTED_BY_MANAGER: "CANDIDATE_REJECTED_BY_MANAGER",
  CONTACT_EXCHANGE_COMPLETED: "CONTACT_EXCHANGE_COMPLETED",

  // Deletion lifecycle
  PROFILE_DELETE_REQUESTED: "PROFILE_DELETE_REQUESTED",
  PROFILE_DELETED: "PROFILE_DELETED",
  VACANCY_DELETE_REQUESTED: "VACANCY_DELETE_REQUESTED",
  VACANCY_DELETED: "VACANCY_DELETED",
} as const;

export type HellyEvent = (typeof HELLY_EVENTS)[keyof typeof HELLY_EVENTS];
